In [1]:
from tensorflow.keras.datasets import imdb

In [2]:
(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)

In [3]:
max([max(sequence) for sequence in train_data])

9999

In [4]:
word_index = imdb.get_word_index()
reverse_word_index = dict([(value, key) for (key, value) in word_index.items()])
decoded_review = ' '.join([reverse_word_index.get(i - 3, '?') for i in train_data[0]])


In [5]:
decoded_review

"? this film was just brilliant casting location scenery story direction everyone's really suited the part they played and you could just imagine being there robert ? is an amazing actor and now the same being director ? father came from the same scottish island as myself so i loved the fact there was a real connection with this film the witty remarks throughout the film were great it was just brilliant so much that i bought the film as soon as it was released for ? and would recommend it to everyone to watch and the fly fishing was amazing really cried at the end it was so sad and you know what they say if you cry at a film it must have been good and this definitely was also ? to the two little boy's that played the ? of norman and paul they were just brilliant children are often left out of the ? list i think because the stars that play them all grown up are such a big profile for the whole film but these children are amazing and should be praised for what they have done don't you th

In [6]:
reverse_word_index[2]

'and'

In [7]:
train_data.shape

(25000,)

In [8]:
import numpy as np
def vectorize_sequences(sequences, dimension=10000):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1
        return results

In [9]:
train_data= vectorize_sequences(train_data)
test_data = vectorize_sequences(test_data)

In [10]:
train_data[2]

array([0., 0., 0., ..., 0., 0., 0.])

In [11]:
test_data[0]

array([0., 1., 1., ..., 0., 0., 0.])

In [12]:
test_labels

array([0, 1, 1, ..., 0, 0, 0], dtype=int64)

In [13]:
train_labels = np.asarray(train_labels).astype('float32')
test_labels = np.asarray(test_labels).astype('float32')

In [14]:
from tensorflow.keras import layers
from tensorflow.keras import models

In [15]:
network = models.Sequential()

In [16]:
network.add(layers.Dense(16,activation = "relu",input_shape = (10000,)))
network.add(layers.Dense(16,activation = "relu"))
network.add(layers.Dense(1,activation = "sigmoid"))

In [17]:
network.compile(optimizer = "rmsprop",loss = "binary_crossentropy",metrics = ["accuracy"])

In [ ]:
network.fit(train_data,train_labels,epochs = 10,batch_size = 512)

Train on 25000 samples
Epoch 1/10
  512/25000 [..............................] - ETA: 1:29 - loss: 0.6931 - accuracy: 0.5137

In [ ]:
train_data.shape