In [1]:
from tensorflow.keras.datasets import mnist

In [2]:
(train_images,train_labels),(test_images,test_labels) = mnist.load_data()

In [3]:
len(train_images)

60000

In [4]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [5]:
from tensorflow.keras.utils import to_categorical

In [6]:
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [7]:
train_labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [8]:
train_images = train_images.reshape(60000,28*28)
train_images = train_images.astype("float")/255
test_images = test_images.reshape(10000,28*28)
test_images = test_images.astype("float")/255

In [9]:
train_images[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [10]:
from tensorflow.keras import layers
from tensorflow.keras import models

In [11]:
network = models.Sequential()

In [16]:
network.add(layers.Dense(16,activation = "relu",input_shape=(28*28,)))
network.add(layers.Dense(10,activation = "softmax"))


In [17]:
network.compile(optimizer='rmsprop',
loss='categorical_crossentropy',
metrics=['accuracy'])

In [20]:
history = network.fit(train_images,train_labels,epochs = 5,batch_size = 128)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 10s 162us/sample - loss: 0.0285 - accuracy: 0.9938
Epoch 2/5
60000/60000 [==============================] - 10s 167us/sample - loss: 0.0203 - accuracy: 0.9955
Epoch 3/5
60000/60000 [==============================] - 9s 158us/sample - loss: 0.0192 - accuracy: 0.9958
Epoch 4/5
60000/60000 [==============================] - 9s 155us/sample - loss: 0.0164 - accuracy: 0.9967
Epoch 5/5
60000/60000 [==============================] - ETA: 0s - loss: 0.0158 - accuracy: 0.99 - 9s 155us/sample - loss: 0.0159 - accuracy: 0.9967


In [19]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc:', test_acc)

10000/1 [===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

In [21]:
dictionary = history.history

In [24]:
dictionary.keys()

dict_keys(['loss', 'accuracy'])